-- ------------------------------------------------------------------
-- Title: The modified multiple organ dysfunction syndrome (MODS) score
-- Reference :
--  Cook R, Cook D, Tilley J, et al. Multiple organ dysfunction: baseline and serial component scores[J]. 
--  Critical care medicine, 2001, 29(11): 2046-2050.
-- ------------------------------------------------------------------

-- ------------------------------------------------------------------------------------------------------------------------
-- organ system                                        0          1             2             3             4
-- ------------------------------------------------------------------------------------------------------------------------
-- Cardiovascular(heart rate, inotropes, lactate)      <=120      120-140       >140          Intropes      Lactate > 5
-- Respiratory, PO2/FIO2                               >300       226-300       151-225       76-150        <=75
-- Renal(creatinine, umol/L)                           <=100      101-200       201-350       351-500       >500
-- Central nervous system(Glasgow Coma Score)          15         13-14         10-12         7-9           <=6
-- Hepatic(total bilirubin, umol/L)                    <=20       21-60         61-120        121-140       >240
-- Hematologic(platelet count *10^3)                   >120       81-120        51-80         21-50         <=20
-- -------------------------------------------------------------------------------------------------------------------------

-- The following views required to run this query:
-- 1). pivoted_bg_art - generated by pivoted-bg.sql
-- 2). pivoted_gcs - generated by pivoted-gcs.sql
-- 3). pivoted_lab - generated by pivoted-lab.sql
-- 4). dopamine_dose - generated by ../durations/dopamine-dose.sql

-- Note:
--  get each hour's MODS value
--  The score is calculated for only adult ICU patients

-- By Xiaoli Liu
-- 2018.05.11


DROP MATERIALIZED VIEW IF EXISTS pivoted_mods CASCADE;
CREATE MATERIALIZED VIEW pivoted_mods AS
-- generate a row for every hour the patient was in the ICU
with co_stg as
(
  select icustay_id, hadm_id
  , date_trunc('hour', intime) as intime
  , outtime
  , generate_series
  (
    -24,
    ceil(extract(EPOCH from outtime-intime)/60.0/60.0)::INTEGER
  ) as hr
  from icustays ie
  inner join patients pt
    on ie.subject_id = pt.subject_id
  -- filter to adults by removing admissions with DOB ~= admission time
  where ie.intime > (pt.dob + interval '1' year)
)

-- add in the charttime column
, co as
(
  select icustay_id, hadm_id, intime, outtime
  , hr*(interval '1' hour) + intime - interval '1' hour as starttime
  , hr*(interval '1' hour) + intime as endtime
  , hr
  from co_stg
)

-- get maximum heart rate from chartevents
, heartrate as
(
  select ce.icustay_id
    , ce.charttime
    , max(valuenum) as hr_max
  from chartevents ce
  -- exclude rows marked as error
  where ce.error IS DISTINCT FROM 1
  and ce.itemid in (211,220045)
  and valuenum > 0 and valuenum < 300
  group by ce.icustay_id, ce.charttime
)

, mini_agg as
(
  select co.icustay_id, co.hr
  -- heart rate 
  , max(heartrate.hr_max) as hr_max
  -- inotropes - dopamine
  , max(vaso_rate) as rate_dopamine  -- mcg/kg/min = ug/kg/min 
  -- respiratory
  , min(bg.pao2fio2ratio) as pao2fio2ratio
  -- gcs
  , min(gcs.GCS) as GCS_min
  -- lab
  , max(labs.lactate) as lactate_max
  , 88.4 * max(labs.creatinine) as creatinine_max  -- mg/dL = 88.4*umol/L
  , 88.4 * max(labs.bilirubin) as bilirubin_max    -- mg/dL = 88.4*umol/L
  , min(labs.platelet) as platelet_min
  from co
  left join heartrate
    on co.icustay_id = heartrate.icustay_id
    and co.starttime < heartrate.charttime
    and co.endtime >= heartrate.charttime
  left join pivoted_gcs gcs
    on co.icustay_id = gcs.icustay_id
    and co.starttime < gcs.charttime
    and co.endtime >= gcs.charttime
  left join pivoted_bg_art bg 
    on co.icustay_id = bg.icustay_id
    and co.starttime < bg.charttime
    and co.endtime >= bg.charttime
  left join pivoted_lab labs
    on co.hadm_id = labs.hadm_id
    and co.starttime < labs.charttime
    and co.endtime >= labs.charttime
  left join dopamine_dose dop 
    on co.icustay_id = dop.icustay_id
    and co.endtime > dop.starttime
    and co.endtime <= dop.endtime
  group by co.icustay_id, co.hr
)

, scorecomp as
(
  select
      co.icustay_id
    , co.hr
    , co.starttime, co.endtime
    , ma.hr_max
    , ma.rate_dopamine
    , ma.pao2fio2ratio
    , ma.GCS_min
    , ma.lactate_max
    , ma.creatinine_max
    , ma.bilirubin_max
    , ma.platelet_min
  from co
  left join mini_agg ma
    on co.icustay_id = ma.icustay_id
    and co.hr = ma.hr
)

, scorecalc as
(
  -- Calculate the final score
  -- note that if the underlying data is missing, the component is null
  -- eventually these are treated as 0 (normal), but knowing when data is missing is useful for debugging
  select scorecomp.*
  -- Cardiovascular
  , case
      when lactate_max > 5   then 4      
      when rate_dopamine > 3 then 3
      when hr_max > 140      then 2
      when hr_max > 120      then 1
      when hr_max > 140      then 2
      when coalesce(lactate_max, rate_dopamine, hr_max) is null then null
      else 0
    end::SMALLINT as cardiovascular

  -- Respiratory
  , case
      when pao2fio2ratio  <= 75  then 4
      when pao2fio2ratio  <= 150 then 3
      when pao2fio2ratio  <= 225 then 2
      when pao2fio2ratio  <= 300 then 1
      when pao2fio2ratio  is null then null
      else 0
    end::SMALLINT as Respiratory

  -- Renal failure 
  , case
      when creatinine_max  >  500  then 4
      when creatinine_max  >  350 then 3
      when creatinine_max  >  200 then 2
      when creatinine_max  >  100 then 1
      when creatinine_max  is null then null
      else 0
    end::SMALLINT as Renal


  -- Neurological failure (GCS)
  , case
      when (GCS_min >= 13 and GCS_min <= 14) then 1
      when (GCS_min >= 10 and GCS_min <= 12) then 2
      when (GCS_min >=  7 and GCS_min <=  9) then 3
      when  GCS_min <=  6 then 4
      when  GCS_min is null then null
  else 0 end::SMALLINT
    as GCS


  -- Hepatic
  , case
      -- Bilirubin checks in umol/L
        when bilirubin_Max >  240  then 4
        when bilirubin_Max >  120  then 3
        when bilirubin_Max >  60   then 2
        when bilirubin_Max >  20   then 1
        when bilirubin_Max is null then null
        else 0
      end::SMALLINT as Hepatic


  -- Hematologic
  , case
      when platelet_min <= 20  then 4
      when platelet_min <= 50  then 3
      when platelet_min <= 80  then 2
      when platelet_min <= 120 then 1
      when platelet_min <= 120 then 1
      when platelet_min is null then null
      else 0
    end::SMALLINT as Hematologic

  from scorecomp
)

, score_final as
(
  select s.*
    -- Combine all the scores to get SOFA
    -- Impute 0 if the score is missing
   -- the window function takes the max over the last 24 hours
    , coalesce(
        MAX(cardiovascular) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)::SMALLINT as cardiovascular_24hours
     , coalesce(
         MAX(respiratory) OVER (PARTITION BY icustay_id ORDER BY HR
         ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
        ,0)::SMALLINT as respiratory_24hours
    , coalesce(
        MAX(renal) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)::SMALLINT as renal_24hours
    , coalesce(
        MAX(GCS) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)::SMALLINT as gcs_24hours
    , coalesce(
        MAX(Hepatic) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)::SMALLINT as hepatic_24hours
    , coalesce(
        MAX(Hematologic) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)::SMALLINT as hematologic_24hours

    -- sum together data for final MODS
    , coalesce(
        MAX(cardiovascular) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)
     + coalesce(
         MAX(respiratory) OVER (PARTITION BY icustay_id ORDER BY HR
         ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)
     + coalesce(
        MAX(renal) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)
     + coalesce(
        MAX(GCS) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)
     + coalesce(
        MAX(hepatic) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)
     + coalesce(
        MAX(hematologic) OVER (PARTITION BY icustay_id ORDER BY HR
        ROWS BETWEEN 24 PRECEDING AND 0 FOLLOWING)
      ,0)::SMALLINT
    as MODS_24hours
  from scorecalc s
)

select * from score_final
where hr >= 0
order by icustay_id, hr;

